default: &default
  orgname: websages.local
  vbox: debian-squeeze-i386
  memory_size: 512
hubot:
  <<: *default
  puppet:
  ports:
    irc:
      host: 6667
      guest: 6667
  mounts:
    hubot_scripts:
      host: ../scripts
      guest: /tmp/hubot_scripts
build:
  <<: *default
  puppet:
